# Generated by Django 4.1 on 2022-08-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='current_time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
