# Generated by Django 4.1 on 2022-08-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.CharField(max_length=2083)),
                ('instagram_url', models.CharField(max_length=2083)),
                ('whatsapp_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
