# Generated by Django 4.1 on 2022-08-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='plat_form',
            new_name='platform',
        ),
    ]
