# Generated by Django 4.1 on 2022-09-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='higher_edu_description',
            field=models.TextField(blank=True),
        ),
    ]
