# Generated by Django 4.1 on 2022-09-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_resume_higher_edu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='college_year',
            field=models.CharField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='resume',
            name='higher_edu_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='inter_edu_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='inter_edu_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='metric_edu_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='metric_edu_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='school_year',
            field=models.CharField(blank=True, max_length=2083),
        ),
        migrations.AlterField(
            model_name='resume',
            name='university_year',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
