# Generated by Django 4.1 on 2022-10-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
