# Generated by Django 4.1 on 2022-10-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_portfolio_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
