# Generated by Django 4.1 on 2022-10-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
