# Generated by Django 4.1 on 2022-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0021_portfolio_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="twitter_url",
            field=models.CharField(default=None, max_length=2083),
        ),
    ]
