# Generated by Django 4.1.3 on 2022-11-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0026_alter_home_twitter_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="twitter_url",
        ),
    ]
