# Generated by Django 4.1.3 on 2022-11-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0028_alter_home_facebook_url_alter_home_instagram_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="twitter_url",
            field=models.CharField(blank=True, default="", max_length=2083, null=True),
        ),
    ]
